### ISSUE TITLE
Improve contents in README.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/CloudConfiguration#17]
Hello @youming-lin, do you have bandwidth to tackle this work item this week?

**Comment by rolivieri** [comment]
Reassigning to Christian.

**Comment by youming-lin** [comment]
Forgot to mention that I had opened a PR with some documentation updates here: #19

**Comment by rolivieri** [comment]
@youming-lin Thanks for letting me know. I did not know you had done some work on this. We will review it, thx.

**Comment by youming-lin** [comment]
I added jazzy docs and cleaned up README a bit but the README is still incomplete. Unfortunately I won't be able to work on this for a while so a reassignment is still preferred :)

**Comment by rolivieri** [comment]
@youming-lin Thanks for working on the task. We will take it from here, no worries.

**Comment by christiancompton** [comment]
Ported to: https://github.ibm.com/arf/planning-swift-solutions/issues/82

**Comment by rolivieri** [comment]
README has been updated.
